### ISSUE TITLE
[NTH] User inputs invalid password

### ISSUE THREAD

**Issue by Duzzuti** [Duzzuti/passwd-manager#1]
- **Difficulty (1-10):**
1
- **Location/Files:**
look in pwfunc/isPasswordValid() and app/askForPasswd()
- **Current behaviour:**
If the user inputs an invalid password, the current response is just a message that the password was illegal.
- **Wished behaviour:**
You have to implement a function that returns why the password was not valid.

**Comment by gautham2k3** [comment]
Assign it t me, I will do that simply by modifying the function

**Comment by Duzzuti** [comment]
yeah that should work

**Comment by dlsf** [comment]
Optimized in #5

**Comment by Duzzuti** [comment]
this issue is still open, no working solution provided

**Comment by Tonystark121** [comment]
@Duzzuti assign me this issue. Give me some brief idea about VALID_PASS_CHARSET which help me solve this issue.

**Comment by Duzzuti** [comment]
yes, `VALID_PASS_CHARSET` is a string which contains characters that are valid. That means that every character of a valid password has to be in this `VALID_PASS_CHARSET`
@dlsf has optimized this string that you can perform an optimal linear search (like its done in the script rn)

**Comment by Duzzuti** [comment]
i think you missunderstood the task.
You have just rewritten the current function.
The target is to give a feedback to the user.
I have an idea: 
-> create a new method getError() which returns a string variable error
-> create this error variable in the class 
-> if we return false because the password was invalid. We will set the error string to something like "password too short"
-> we can call getError if the password is invalid to get the exact error message

but get your own idea. The user has to get a message like: `there is an invalid character " " in the password`
