### ISSUE TITLE
[NTH] more ChainHash functions

### ISSUE THREAD

**Issue by Duzzuti** [Duzzuti/passwd-manager#3]
- **Difficulty (1-10):**
3
- **Location/Files:**
pwfunc.h/pwfunc.cpp
- **Current behaviour:**
A chainhash is an hash which is applied on its previous result (for a given number of iterations).
You can copy some code from the implemented chainhashes.
use this->hash->hash() as the hash function. 
there are already 4 types of chainhashes imnplemented.:
  1. A chainhash which hashes the last hash again
  2. A chainhash which hashes the last hash + a constant salt
  3. A chainhash which hashes the last hash + an incrementing number
  4. A chainhash which hashes the last hash + a constant salt + an incrementing number
- **Wished behaviour:**
*New chainhashes wished*
Define you own chainhash function in the pwfunc files.
Constraints:
    1. it has to take  at least a std::string password and an iteration number
    2. it can take more arguments if needed, but all added arguments have to be under 256 Bytes memory (because we have to save them in a buffer, this constraint is more theoretically but you should not expect long strings or other big data to get passed)
    3. the result has to be the same with the same arguments (obviously)

*if you need help or have a hard time understanding certain things, you are welcome to comment on this issue*

**Good luck**

**Comment by MirrorCraze** [comment]
Hi! Would you mind assigning this to me? I have some possible thoughts on it.

For example, extending from using the incrementing number only, we can use some kinds of a*(iteration)^2 + b*(iteration) + c (where a,b,c is given as parameter) to add with the last hash.

**Comment by Duzzuti** [comment]
nice idea, lets try it out

**Comment by Duzzuti** [comment]
this issue is still open, i am looking forward to see your solutions

**Comment by Duzzuti** [comment]
reopened in a new issue #12
